// Frontend/Vuejs/src/page/Task/TaskPage.vue
<template>
  <div>
    <span class="lg:flex flex-row">
      <router-link
        class="max-h-9 mr-2 p-2 bg-blue-600 text-white rounded-lg"
        :to="'../'"
      >
        Go back
      </router-link>
      <h1 class="text-5xl mb-8">Todo-List App</h1>
    </span>
    <h2 class="text-3xl mb-8">My list</h2>
    <div>
      <TaskCreation
        :refreshTask="refreshTask"
        :projectId="id"
      ></TaskCreation>
      <hr class="mt-2 mb-2" />
      <Task
        v-for="task in tasks"
        :key="task.id"
        :id="task.id"
        :done="task.done"
        :name="task.name"
        :refreshTask="refreshTask"
      ></Task>
    </div>
  </div>
</template>

<script>
import { ref, onMounted, reactive } from 'vue';
import { useRoute } from 'vue-router';
import TaskCreation from '../../components/Task/TaskCreation.vue';
import Task from '../../components/Task/Task.vue';
import { getTasks } from '../../services/Services';

export default {
  components: {
    TaskCreation,
    Task,
  },
  setup() {
    const route = useRoute();
    const id = ref(route.params.id);
    const tasks = ref([]);

    const refreshTask = () => {
      getTasks(id.value)
          .then((data) => {
            tasks.value = data;
          })
          .catch((error) => {
            console.log(error);
          })
          .finally(() => {
            console.log("updated")
      });
    };

    onMounted(() => {
      if (id.value) {
        getTasks(id.value)
          .then((data) => {
            tasks.value = data;
          })
          .catch((error) => {
            console.log(error);
          })
          .finally(() => {
            console.log("updated")
          });
      }
    });

    return {
      id,
      tasks,
      refreshTask,
    };
  },
};
</script>

<style>
/* Add your CSS styles here */
</style>

// Frontend/React/src/page/Task/TaskPage.tsx
import { useState, useEffect } from "react";
import { Link, useParams } from "react-router-dom";
import TaskCreation from "../../components/Task/TaskCreation";
import Task from "../../components/Task/Task";
import { getTasks } from "../../services/Services";

const TaskPage = () => {

  let { id } = useParams();

  const [tasks, setTasks] = useState<any[]>([]);
  const [update, setUpdate] = useState<boolean>(true);

  useEffect(() => {
    if (id && update) {
      getTasks(id).then((data) => {
        setTasks(data);
      }).catch((error) => {
        console.log(error);
      }).finally(() => {
        setUpdate(false);
      });
    }
  }, [id, update]);

  return (
    <>
        <span className="lg:flex flex-row">
          <Link className="max-h-9 mr-2 p-2 bg-blue-600 text-white rounded-lg"
            to='../'>Go back</Link>
          <h1 className='text-5xl mb-8'>Todo-List App</h1>
        </span>
        <h2 className='text-3xl mb-8'>My list</h2>
        <div className=''>
          <TaskCreation
            refreshTask={() => { setUpdate(true) }}
            projectId={id!}
          ></TaskCreation>
          <hr className="mt-2 mb-2" />
          {tasks?.map((task) => {
            return <Task key={task.id}
              id={task.id}
              done={task.done}
              name={task.name}
              refreshTask={
                () => { setUpdate(true) }}
            />
          })}
        </div>
      </>
  )
}

export default TaskPage;
