// Frontend/Vuejs/src/App.vue
<template>
  <main class="flex min-h-screen items-center justify-center p-24">
    <div class="z-10 w-full max-w-5xl items-center justify-center align-center font-mono text-sm flex-col lg:flex">
      <router-view></router-view>
    </div>
  </main>
</template>

<script lang="ts">

export default {
  name: 'App'
};
</script>

<style scoped>
</style>

// React/src/App.tsx
import './App.css';

import {
  BrowserRouter,
  Route,
  Routes
} from "react-router-dom";
import ProjectPage from './page/Project/ProjectPage';
import TaskPage from './page/Task/TaskPage';

function App() {
  return (
    <main className="flex min-h-screen  items-center justify-center p-24">
      <div className="z-10 w-full max-w-5xl items-center justify-center align-center font-mono text-sm flex-col lg:flex">
    <BrowserRouter>
      <Routes>
        <Route path="/" element={<ProjectPage />} />
        <Route path="/project/:id" element={<TaskPage />} />
      </Routes>
    </BrowserRouter>
      </div>
    </main>
  );
}

export default App;
