// Angular/src/app/taskpage/taskpage.component.ts
import { Component } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { Subscription } from 'rxjs';
import { AppService } from '../app.service';

@Component({
  selector: 'app-taskpage',
  templateUrl: './taskpage.component.html',
  styleUrls: ['./taskpage.component.css']
})
export class TaskpageComponent {

  tasks: any[] = [];
  update: boolean = true;
  projectId: string | null = null;

  constructor(private route: ActivatedRoute, private service: AppService){

  }

  ngOnInit() {
    this.route.params.subscribe((params) => {
      this.projectId = params.id;
      this.updateTasks();
    });
  }

  updateTasks() {
    if (this.projectId) {
      this.service.getTasks(this.projectId).subscribe((response : any) => {
        this.tasks = response?.items;
      });
    }
  }

}

<div class="z-10 w-full max-w-5xl items-center justify-center align-center font-mono text-sm flex-col lg:flex">
    <span class="lg:flex flex-row">
        <a class="max-h-9 mr-2 p-2 bg-blue-600 text-white rounded-lg" [routerLink]="['../']">Go back</a>
        <h1 class="text-5xl mb-8">Todo-List App</h1>
    </span>
    <h2 class="text-3xl mb-8">My list</h2>
    <div>
        <app-task-creation (refreshTask)="updateTasks()" [projectId]="projectId"></app-task-creation>
        <hr class="mt-2 mb-2" />
        <app-task *ngFor="let task of tasks" [id]="task.id" [done]="task.done" [name]="task.name"
            (refreshTask)="updateTasks()"></app-task>
    </div>
</div>

// React/src/page/Task/TaskPage.tsx
import { useState, useEffect } from "react";
import { Link, useParams } from "react-router-dom";
import TaskCreation from "../../components/Task/TaskCreation";
import Task from "../../components/Task/Task";
import { getTasks } from "../../services/Services";

const TaskPage = () => {

  let { id } = useParams();

  const [tasks, setTasks] = useState<any[]>([]);
  const [update, setUpdate] = useState<boolean>(true);

  useEffect(() => {
    if (id && update) {
      getTasks(id).then((data) => {
        setTasks(data);
      }).catch((error) => {
        console.log(error);
      }).finally(() => {
        setUpdate(false);
      });
    }
  }, [id, update]);

  return (
    <main className="flex min-h-screen  items-center justify-center p-24">
      <div className="z-10 w-full max-w-5xl items-center justify-center align-center font-mono text-sm flex-col lg:flex">
        <span className="lg:flex flex-row">
          <Link className="max-h-9 mr-2 p-2 bg-blue-600 text-white rounded-lg"
            to='../'>Go back</Link>
          <h1 className='text-5xl mb-8'>Todo-List App</h1>
        </span>
        <h2 className='text-3xl mb-8'>My list</h2>
        <div className=''>
          <TaskCreation
            refreshTask={() => { setUpdate(true) }}
            projectId={id!}
          ></TaskCreation>
          <hr className="mt-2 mb-2" />
          {tasks?.map((task) => {
            return <Task key={task.id}
              id={task.id}
              done={task.done}
              name={task.name}
              refreshTask={
                () => { setUpdate(true) }}
            />
          })}
        </div>
      </div>
    </main>
  )
}

export default TaskPage;
