// Vuejs/vue-project/src/components/Task/Task.vue
<template>
  <div class="flex-row lg:flex items-center mb-2">
    <input
      type="checkbox"
      class="form-checkbox h-5 w-5 text-gray-600"
      v-model="inputDone"
      @change="handleCheckboxChange"
    />
    <template v-if="isEditing">
      <input
        type="text"
        class="form-input ml-2 text-gray-700"
        v-model="inputName"
        @blur="handleInputBlur"
        autofocus
      />
    </template>
    <template v-else>
      <span class="ml-2 text-white-700" @click="handleSpanClick">
        {{ inputName }}
      </span>
    </template>
    <button
      class="ml-2 p-2 bg-red-600 text-white rounded-lg ml-auto"
      @click="callDelete"
    >
      (-)
    </button>
  </div>
</template>

<script>
import { ref } from 'vue';
import { deleteTask, updateTask } from '../../services/Services';

export default {
  props: {
    id: {
      type: String,
      required: true,
    },
    name: {
      type: String,
      required: true,
    },
    done: {
      type: Boolean,
      required: true,
    },
    refreshTask: {
      type: Function,
      required: true,
    },
  },
  setup(props) {
    const isEditing = ref(false);
    const inputName = ref(props.name || '');
    const inputDone = ref(props.done || false);

    const handleSpanClick = () => {
      isEditing.value = true;
    };

    const handleInputChange = (event) => {
      inputName.value = event.target.value;
    };

    const handleCheckboxChange = () => {
      updateTask({ id: props.id, name: inputName.value, done: inputDone.value })
        .finally(() => {
          props.refreshTask();
        });
    };

    const handleInputBlur = () => {
      isEditing.value = false;
      updateTask({ id: props.id, name: inputName.value, done: inputDone.value })
        .finally(() => {
          props.refreshTask();
        });
    };

    const callDelete = () => {
      deleteTask(props.id).finally(() => {
        props.refreshTask();
      });
    };

    return {
      isEditing,
      inputName,
      inputDone,
      handleSpanClick,
      handleInputChange,
      handleCheckboxChange,
      handleInputBlur,
      callDelete,
    };
  },
};
</script>

<style>
/* Add your CSS styles here */
</style>

// Frontend/React/src/components/Task/Task.tsx
import { SyntheticEvent, useState } from "react";
import { deleteTask, updateTask } from "../../services/Services";

interface TaskProps {
  id:string;
  name:string;
  done:boolean;
  refreshTask: ()=>void;
}
const Task = ( task : TaskProps)=>{
  const { id, name, done, refreshTask } = task;

  const [isEditing, setIsEditing] = useState(false);
  const [inputName, setInputName] = useState(name ?? '');
  const [inputDone, setInputDone] = useState<boolean>(done ?? false);

  const handleSpanClick = () => {
    setIsEditing(true);
  };

  const handleInputChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setInputName(event.target.value);
  };

  const handleCheckboxChange = () => {
    updateTask({id:id,name:inputName,done:!inputDone})
      .finally(()=>{
        refreshTask()
      });
    setInputDone((prev)=>!prev);
  };

  const handleInputBlur = () => {
    setIsEditing(false);
    updateTask({id:id,name:inputName,done:inputDone})
      .finally(()=>{
        refreshTask()
      });;
  };

  const callDelete = ()=>{
    deleteTask(id).finally(()=>{ 
      refreshTask() 
    });
  }
    

  return (
    <div className='flex-row lg:flex items-center mb-2'>
      <input type="checkbox" className="form-checkbox h-5 w-5 text-gray-600" onChange={handleCheckboxChange} checked={inputDone} />
      {isEditing ? (
        <input
          type='text'
          className='form-input ml-2 text-gray-700'
          value={inputName}
          onChange={handleInputChange}
          onBlur={handleInputBlur}
          autoFocus
        />
      ) : (
        <span className='ml-2 text-white-700' onClick={handleSpanClick}>
          {inputName}
        </span>
      )}
      <button 
        className="ml-2 p-2 bg-red-600 text-white rounded-lg ml-auto"
        onClick={callDelete}  
      >(-)</button>
    </div>
  )
}
export default Task;
