// Angular/src/app/taskcreation/taskcreation.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { AppService } from '../app.service';

@Component({
  selector: 'app-task-creation',
  templateUrl: './taskcreation.component.html',
  styleUrls: ['./taskcreation.component.css']
})
export class TaskcreationComponent {

  @Output() refreshTask = new EventEmitter<void>();
  @Input() projectId: string | null = null;
  name: string = '';

  constructor(private service: AppService) {}

  createTask() {
    if (this.projectId) {
      this.service.createTask(this.projectId,this.name).subscribe(() => {
        this.refreshTask.emit();
      });
    }
  }
}

<div>
    <input
      class='text-black ml-2 border border-gray-300 rounded-lg p-2'
      [(ngModel)]="name"
      type="text"
    />
    <button
      class='ml-2 p-2 bg-blue-600 text-white rounded-lg'
      (click)="createTask()"
    >(+)</button>
</div>

// Frontend/React/src/components/Task/TaskCreation.tsx
import { useState } from "react";
import { createTask } from "../../services/Services";

interface TaskCreationProps {
    refreshTask: ()=>void;
    projectId: string;
}
const TaskCreation = ({ refreshTask, projectId }: TaskCreationProps)=>{

    const [name,setName] = useState<string>('');

    const handleInputChange = (event: any) => {
      setName(event.target.value);
    };

    const callCreate = ()=>{
        createTask(name,projectId).finally(()=>{
            refreshTask();
        });
    }

    return (
        <div>
            <input
                className='text-black ml-2 border border-gray-300 rounded-lg p-2'
                value={name}
                type="text"
                onChange={handleInputChange}
            />
            <button
                className='ml-2 p-2 bg-blue-600 text-white rounded-lg'
                onClick={callCreate}
            >(+)</button>
        </div>
    )
}

export default TaskCreation;
