// Angular/src/app/task/task.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { Task } from '../../model/task.model';
import { AppService } from '../app.service';

@Component({
  selector: 'app-task',
  templateUrl: './task.component.html',
  styleUrls: ['./task.component.css']
})
export class TaskComponent {

  @Input() task: Task = { id: '', name: '', done: false };
  @Output() refreshTask = new EventEmitter<void>();

  isEditing: boolean = false;
  public inputName: string = '';
  inputDone: boolean = false;

  constructor(private service: AppService) {
  }

  ngOnInit() {
    const { name, done } = this.task;
    this.inputName = name ?? '';
    this.inputDone = done ?? false;
  }

  handleSpanClick() {
    this.isEditing = true;
  }

  handleCheckboxChange() {
    this.updateTask({ id: this.task.id, name: this.inputName, done: !this.inputDone });
    this.inputDone = !this.inputDone;
  }

  handleInputBlur() {
    this.isEditing = false;
    this.updateTask({ id: this.task.id, name: this.inputName, done: this.inputDone });
  }

  deleteTask() {
    this.service.deleteTask(this.task.id).subscribe(() => {
      this.refreshTask.emit();
    });
  }

  updateTask(task: Task) {
    this.service.updateTask(task).subscribe(() => {
      this.refreshTask.emit();
    });
  }

}

<div class='flex-row lg:flex items-center mb-2'>
    <input type="checkbox" class="form-checkbox h-5 w-5 text-gray-600" (change)="handleCheckboxChange()" [checked]="inputDone" />
    <ng-container *ngIf="isEditing; else viewMode">
      <input
        type='text'
        class='form-input ml-2 text-gray-700'
        (blur)="handleInputBlur()"
        [(ngModel)]="inputName"
        autofocus
      />
    </ng-container>
    <ng-template #viewMode>
      <span class='ml-2 text-white-700' (click)="handleSpanClick()">
        {{ inputName }}
      </span>
    </ng-template>
    <button 
      class="ml-2 p-2 bg-red-600 text-white rounded-lg ml-auto"
      (click)="deleteTask()"
    >(-)</button>
</div>

// Vuejs/vue-project/src/components/Task/Task.vue
<template>
  <div class="flex-row lg:flex items-center mb-2">
    <input
      type="checkbox"
      class="form-checkbox h-5 w-5 text-gray-600"
      v-model="inputDone"
      @change="handleCheckboxChange"
    />
    <template v-if="isEditing">
      <input
        type="text"
        class="form-input ml-2 text-gray-700"
        v-model="inputName"
        @blur="handleInputBlur"
        autofocus
      />
    </template>
    <template v-else>
      <span class="ml-2 text-white-700" @click="handleSpanClick">
        {{ inputName }}
      </span>
    </template>
    <button
      class="ml-2 p-2 bg-red-600 text-white rounded-lg ml-auto"
      @click="callDelete"
    >
      (-)
    </button>
  </div>
</template>

<script>
import { ref } from 'vue';
import { deleteTask, updateTask } from '../../services/Services';

export default {
  props: {
    id: {
      type: String,
      required: true,
    },
    name: {
      type: String,
      required: true,
    },
    done: {
      type: Boolean,
      required: true,
    },
    refreshTask: {
      type: Function,
      required: true,
    },
  },
  setup(props) {
    const isEditing = ref(false);
    const inputName = ref(props.name || '');
    const inputDone = ref(props.done || false);

    const handleSpanClick = () => {
      isEditing.value = true;
    };

    const handleInputChange = (event) => {
      inputName.value = event.target.value;
    };

    const handleCheckboxChange = () => {
      updateTask({ id: props.id, name: inputName.value, done: inputDone.value })
        .finally(() => {
          props.refreshTask();
        });
    };

    const handleInputBlur = () => {
      isEditing.value = false;
      updateTask({ id: props.id, name: inputName.value, done: inputDone.value })
        .finally(() => {
          props.refreshTask();
        });
    };

    const callDelete = () => {
      deleteTask(props.id).finally(() => {
        props.refreshTask();
      });
    };

    return {
      isEditing,
      inputName,
      inputDone,
      handleSpanClick,
      handleInputChange,
      handleCheckboxChange,
      handleInputBlur,
      callDelete,
    };
  },
};
</script>

<style>
/* Add your CSS styles here */
</style>
